pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name 'ParchmentMC'
            url 'https://maven.parchmentmc.org'
        }
        maven {
            name = 'NeoForge'
            url = uri("https://maven.neoforged.net/releases")
        }
    }
    resolutionStrategy {
        eachPlugin {
            switch (requested.id.toString()) {
                case "net.neoforged.moddev-gradle": {
                    useModule("${requested.id}:moddev-gradle:${requested.version}")
                    break
                }
            }
        }
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = "mk-platform-${minecraft_version}"

include 'TargetingAPI'
include 'MKWidgets'
include 'MKCore'
include 'MKChat'
include 'MKFaction'
include 'MKWeapons'
include 'MKNpc'
include 'MKUltra'
include 'MKIAFCompat'

