plugins {
    id "mk-platform"
}


version = "${minecraft_version}-${mk_core_version}"
project.ext.mod_version = mk_core_version
project.ext.dependentProjects = [
        project(":TargetingAPI"),
        project(":MKWidgets")
]

apply from: '../common.gradle'

idea.module {
    excludeDirs << file("run")
}
