plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version "${mdg_version}"
}


version = "${minecraft_version}-${mk_core_version}"
project.ext.mod_version = mk_core_version
project.ext.dependentProjects = [
        project(":TargetingAPI"),
        project(":MKWidgets")
]

apply from: '../common.gradle'

dependencies {
    compileOnly "maven.modrinth:uranus:fOkq6VwW"
    compileOnly "maven.modrinth:jupiter:6FVn8sRM"
    compileOnly "maven.modrinth:iceandfire-ce:vS8ELZ5k"
}