plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version "${mdg_version}"
}


version = "${minecraft_version}-${mk_npc_version}"
project.ext.mod_version = mk_npc_version
project.ext.dependentProjects = [
        project(":TargetingAPI"),
        project(":MKWidgets"),
        project(":MKCore"),
        project(":MKChat"),
        project(":MKFaction"),
        project(":MKWeapons")
]

apply from: '../common.gradle'

def gameTestDir = file('run-gametest')

tasks.register('cleanGameTestWorld', Delete) {
    delete gameTestDir
}

tasks.named('prepareGameTestServerRun').configure {
    gameDirectory = gameTestDir
}

tasks.named('runGameTestServer').configure {
    dependsOn tasks.named('cleanGameTestWorld')
}

neoForge {
    validateAccessTransformers = true

    runs {
        gameTestServer {
            gameDirectory = gameTestDir
        }
    }
}
