package com.chaosbuffalo.mkcore.abilities2.runtime;

public enum FailureReason {
    UNKNOWN_ABILITY,
    UNKNOWN_ACTIVATION,
    ACTIVATION_NOT_EXTERNALLY_CALLABLE,
    INVALID_TARGETS,
    NOT_ENOUGH_RESOURCE,
    ON_COOLDOWN,
    BUSY,
    INTERRUPTED,
    INTERRUPTED_BY_BLOCK,
    INTERRUPTED_BY_JUMP,
    INTERRUPTED_BY_MOVE,
    INTERRUPTED_BY_DAMAGE,
    INTERRUPTED_BY_STUN,
    INTERRUPTED_BY_DEATH,
    INTERRUPTED_BY_LOGOUT,
    INTERRUPTED_BY_UNLOAD,
    TARGET_LOST,
    UNSUPPORTED_FEATURE
}
