plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version "${mdg_version}"
}


version = "${minecraft_version}-${mk_ultra_version}"
project.ext.mod_version = mk_ultra_version
project.ext.dependentProjects = [
        project(":TargetingAPI"),
        project(":MKWidgets"),
        project(":MKCore"),
        project(":MKChat"),
        project(":MKFaction"),
        project(":MKWeapons"),
        project(":MKNpc")
]

apply from: '../common.gradle'

dependencies {
    compileOnly project(":MKWorkspaceRuntime")
    compileOnly project(":MKWorkspace")
    compileOnly project(":MKWorkspaceExtensions")
    localRuntime project(":MKWorkspace")
    localRuntime project(":MKWorkspaceExtensions")
}

neoForge {
    runs {
        data {
            programArguments.addAll '--existing-mod', 'mkweapons'
        }
    }
}
