plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version "${mdg_version}"
}


version = "${minecraft_version}-${mk_iaf_compat_version}"
project.ext.mod_version = mk_iaf_compat_version
project.ext.dependentProjects = [
        project(":MKCore"),
        project(":MKFaction")
]

apply from: '../common.gradle'


dependencies {
    implementation "maven.modrinth:uranus:fOkq6VwW"
    implementation "maven.modrinth:jupiter:6FVn8sRM"
    implementation "maven.modrinth:iceandfire-ce:vS8ELZ5k"
}