modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[${forge_loader_version},)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
issueTrackerURL = "https://github.com/ChaosBuffalo/TargetingAPI/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "${mod_id}" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version = "${base_version}" #mandatory
# A display name for the mod
displayName = "${mod_name}" #mandatory
credits = "Developed by the MK Ultra Team" #optional
description = '''
A Targeting API to assist modders in determining entity relationships.
'''
[[dependencies."${mod_id}"]]
    modId = "forge"
    mandatory = true
    versionRange = "[${forge_version},)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies."${mod_id}"]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${mc_version},${mc_version_end})"
    ordering = "NONE"
    side = "BOTH"
