plugins {
    id "mk-platform"
}


version = "${minecraft_version}-${mk_weapons_version}"
project.ext.mod_version = mk_weapons_version
project.ext.dependentProjects = [
        project(":TargetingAPI"),
        project(":MKWidgets"),
        project(":MKCore")
]
project.ext.extra_properties = [
        curios_version: curios_version
]

apply from: '../common.gradle'

processResources {
    exclude '.cache'
    duplicatesStrategy(DuplicatesStrategy.FAIL)
}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
            exclude('.cache')
        }
    }
}

dependencies {
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
    implementation "top.theillusivec4.curios:curios-neoforge:${curios_version}"
}
