plugins {
    id "mk-platform"
}


version = "${minecraft_version}-${mk_faction_version}"
project.ext.mod_version = mk_faction_version
project.ext.dependentProjects = [
        project(":TargetingAPI"),
        project(":MKWidgets"),
        project(":MKCore")
]

apply from: '../common.gradle'

idea.module {
    excludeDirs << file("run")
}
