plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal() // so that external plugins can be resolved in dependencies section
    maven {
        name = 'NeoForge'
        url = uri("https://maven.neoforged.net/releases")
    }
    maven { url = 'https://maven.parchmentmc.org' }
}

dependencies {
    implementation group: 'net.neoforged', name: 'moddev-gradle', version: '1.0.17', changing: true
}
